config/routes.rb
Rails.application.routes.draw do
  get "battles/index"
  get "battles/show"
  root 'home#index' # This sets the home page

  resources :emperors, only: [:index, :show]
  resources :roman_places, only: [:index, :show]
  resources :gods, only: [:index, :show]
  resources :battles, only: [:index, :show]
  resources :museums, only: [:index, :show]
  resources :army_units, only: [:index, :show]
  resources :roman_inventions, only: [:index, :show]
  # ... other routes ...
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/army_unit.rb
class ArmyUnit < ApplicationRecord
end

app/models/battle.rb
class Battle < ApplicationRecord
end

app/models/emperor.rb
class Emperor < ApplicationRecord
end

app/models/god.rb
class God < ApplicationRecord
end

app/models/museum.rb
class Museum < ApplicationRecord
end

app/models/roman_invention.rb
class RomanInvention < ApplicationRecord
end

app/models/roman_place.rb
class RomanPlace < ApplicationRecord
end

app/controllers/army_units_controller.rb
class ArmyUnitsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  def index
    @battles = Battle.all
  end

  def show
    @battle = Battle.find(params[:id])
  end
end

app/controllers/emperors_controller.rb
class EmperorsController < ApplicationController
  def index
    @emperors_by_category = Emperor.all.group_by(&:category)
  end

  def show
    @emperor = Emperor.find(params[:id]) # Find a specific emperor by their ID
  end
end

app/controllers/gods_controller.rb
class GodsController < ApplicationController
  def index
    @gods_by_realm=God.all.group_by(&:realm)
  end

  def show
    @god = God.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
    def index
      @museums_by_region=Museum.all.group_by(&:region)
    end
    
    def show
      @museum=Museum.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/army_units_helper.rb
module ArmyUnitsHelper
end

app/helpers/battles_helper.rb
module BattlesHelper
end

app/helpers/emperors_helper.rb
module EmperorsHelper
end

app/helpers/gods_helper.rb
module GodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/museums_helper.rb
module MuseumsHelper
end

app/helpers/roman_inventions_helper.rb
module RomanInventionsHelper
end

app/views/home/index.html.erb
<h1>Roman History For Kids</h1>
<div class="home-container">
<p>Welcome to roman history for kids, Here you can explore the fascinating world of the roman empire.</p>
<h2>Explore Topics</h2>
<ul>
  <li><%= link_to "Roman Emperors", emperors_path %> - Discover the powerful rulers of the Roman Empire!</li>
  <li><%= link_to "Historical Roman Places", roman_places_path %> - Explore amazing ancient sites and landmarks!</li>
  <li><%= link_to "Roman Gods & Mythology", gods_path %> - Discover the powers and stories of the almighty gods worshipped by the romans!</li>
  <li><%= link_to "Important Roman Battles", battles_path %> - Discover important battles that shaped the future of Rome!</li>
  <li><%= link_to "Museums With Roman Exhibits", museums_path %> - Find museums in the uk that include roman exhibits!</li>
  <li><% link_to "Types Of Units In An Army", army_units_path %> - Find out what units made up the Roman army!</li>
  <li><%= link_to "Roman Inventions", roman_inventions_path %> - find out about the many inventions we have the romans to thank for!</li>
</ul>
</div>