config/routes.rb
Rails.application.routes.draw do
  get "battles/index"
  get "battles/show"
  root 'home#index' # This sets the home page

  resources :emperors, only: [:index, :show]
  resources :roman_places, only: [:index, :show]
  resources :gods, only: [:index, :show]
  resources :battles, only: [:index, :show]
  resources :museums, only: [:index, :show]
  resources :army_units, only: [:index, :show]
  resources :roman_inventions, only: [:index, :show]
  # ... other routes ...
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/army_unit.rb
class ArmyUnit < ApplicationRecord
end

app/models/battle.rb
class Battle < ApplicationRecord
end

app/models/emperor.rb
class Emperor < ApplicationRecord
end

app/models/god.rb
class God < ApplicationRecord
end

app/models/museum.rb
class Museum < ApplicationRecord
end

app/models/roman_invention.rb
class RomanInvention < ApplicationRecord
end

app/models/roman_place.rb
class RomanPlace < ApplicationRecord
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  def index
    @battles = Battle.all
  end

  def show
    @battle = Battle.find(params[:id])
  end
end

app/controllers/emperors_controller.rb
class EmperorsController < ApplicationController
  def index
    @emperors_by_category = Emperor.all.group_by(&:category)
  end

  def show
    @emperor = Emperor.find(params[:id]) # Find a specific emperor by their ID
  end
end

app/controllers/gods_controller.rb
class GodsController < ApplicationController
  def index
    @gods_by_realm=God.all.group_by(&:realm)
  end

  def show
    @god = God.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
    def index
      @museums_by_region=Museum.all.group_by(&:region)
    end
    
    def show
      @museum=Museum.find(params[:id]) 
    end
end

app/controllers/roman_places_controller.rb
class RomanPlacesController < ApplicationController
    def index
      @roman_places_by_category = RomanPlace.all.group_by(&:category)
    end
  
    def show
      @roman_place = RomanPlace.find(params[:id])
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/army_units_helper.rb
module ArmyUnitsHelper
end

app/helpers/battles_helper.rb
module BattlesHelper
end

app/helpers/emperors_helper.rb
module EmperorsHelper
end

app/helpers/gods_helper.rb
module GodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/museums_helper.rb
module MuseumsHelper
end

app/helpers/roman_inventions_helper.rb
module RomanInventionsHelper
end

app/views/roman_places/index.html.erb
<h1>Historical Roman Places by Category</h1>

<div class="categories-container">
  <% @roman_places_by_category.each do |category, places| %>
    <div class="category-group">
      <h2><%= category %></h2>
      <ul>
        <% places.each do |place| %>
          <li><%= link_to place.name, roman_place_path(place) %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

<%= link_to 'Back to Home', root_path %>

<style>
  .categories-container {
    display: flex;
    flex-wrap: wrap;
    gap: 20px;
  }

  .category-group {
    flex: 1 0 200px; /* Adjust width as needed */
    border: 1px solid #ccc;
    padding: 15px;
    border-radius: 5px;
  }

  .category-group h2 {
    margin-top: 0;
    color: #8B4513; /* Example color */
  }

  .category-group ul {
    list-style: none;
    padding: 0;
  }

  .category-group li {
    margin-bottom: 5px;
  }
</style>

app/views/roman_places/show.html.erb
<div class="fact-file-box">
  <h1><%= @roman_place.name %></h1>

  <p><strong>Location:</strong> <%= @roman_place.location %></p>
  <p><%= simple_format(@roman_place.description) %></p>
  <p><strong>Fun Fact:</strong> <%= @roman_place.fun_fact %></p>
  <p><strong>Approximate Build Date:</strong>
    <% if @roman_place.build_date.present? %>
      <% if @roman_place.build_date < 0 %>
        <%= -@roman_place.build_date %> BC
      <% else %>
        <%= @roman_place.build_date %> AD
      <% end %>
    <% end %>
  </p>
  <% if @roman_place.image_url.present? %>
    <%= image_tag @roman_place.image_url, alt: @roman_place.name %>
  <% end %>

  <div class="back-links">
    <%= link_to 'Back to Roman Places', roman_places_path %> |
    <%= link_to 'Back to Home', root_path %>
  </div>
</div>