config/routes.rb
Rails.application.routes.draw do
  get "battles/index"
  get "battles/show"
  root 'home#index' # This sets the home page

  resources :emperors, only: [:index, :show]
  resources :roman_places, only: [:index, :show]
  resources :gods, only: [:index, :show]
  resources :battles, only: [:index, :show]
  resources :museums, only: [:index, :show]
  resources :army_units, only: [:index, :show]
  resources :roman_inventions, only: [:index, :show]
  # ... other routes ...
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/army_unit.rb
class ArmyUnit < ApplicationRecord
end

app/models/battle.rb
class Battle < ApplicationRecord
end

app/models/emperor.rb
class Emperor < ApplicationRecord
end

app/models/god.rb
class God < ApplicationRecord
end

app/models/museum.rb
class Museum < ApplicationRecord
end

app/models/roman_invention.rb
class RomanInvention < ApplicationRecord
end

app/models/roman_place.rb
class RomanPlace < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/army_units_controller.rb
class ArmyUnitsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  def index
    @battles = Battle.all
  end

  def show
    @battle = Battle.find(params[:id])
  end
end

app/controllers/emperors_controller.rb
class EmperorsController < ApplicationController
  def index
    @emperors_by_category = Emperor.all.group_by(&:category)
  end

  def show
    @emperor = Emperor.find(params[:id]) # Find a specific emperor by their ID
  end
end

app/controllers/gods_controller.rb
class GodsController < ApplicationController
  def index
    @gods_by_realm=God.all.group_by(&:realm)
  end

  def show
    @god = God.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
    def index
      @museums_by_region=Museum.all.group_by(&:region)
    end
    
    def show
      @museum=Museum.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/army_units_helper.rb
module ArmyUnitsHelper
end

app/helpers/battles_helper.rb
module BattlesHelper
end

app/helpers/emperors_helper.rb
module EmperorsHelper
end

app/helpers/gods_helper.rb
module GodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/museums_helper.rb
module MuseumsHelper
end

app/helpers/roman_inventions_helper.rb
module RomanInventionsHelper
end

app/views/army_units/index.html.erb
<h1>ArmyUnits#index</h1>
<p>Find me in app/views/army_units/index.html.erb</p>

app/views/army_units/show.html.erb
<h1>ArmyUnits#show</h1>
<p>Find me in app/views/army_units/show.html.erb</p>

app/views/battles/index.html.erb
<h1>Important Roman Battles</h1>

<div class="battle-list-container"> <ul>
    <% @battles.each do |battle| %>
      <li><%= link_to battle.name, battle_path(battle) %></li>
    <% end %>
  </ul>
</div>

<%= link_to 'Back to Home', root_path %>

app/views/battles/show.html.erb
<div class="fact-file-box">
  <h1><%= @battle.name %></h1>
  <p><strong>Date:</strong> <%= @battle.date %></p>
  <p><strong>Location:</strong> <%= @battle.location %></p>
  <p><strong>Belligerents:</strong> <%= @battle.belligerents %></p>
  <p><strong>Outcome:</strong> <%= @battle.outcome %></p>
  <p><strong>Why it was Important (for Kids):</strong> <%= @battle.importance %></p>
  <% if @battle.image_url.present? %>
    <%= image_tag @battle.image_url, alt: @battle.name %>
  <% end %>
  <div class="back-links">
    <%= link_to 'Back to Battles', battles_path %> |
    <%= link_to 'Back to Home', root_path %>
  </div>
</div>

app/views/emperors/index.html.erb
<h1>Roman Emperors by Category</h1>

<div class="categories-container">
  <% @emperors_by_category.each do |category, emperors| %>
    <div class="category-group">
      <h2><%= category %></h2>
      <ul>
        <% emperors.each do |emperor| %>
          <li><%= link_to emperor.name, emperor_path(emperor) %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/emperors/show.html.erb
<div class="emperor-details">
<h1><%= @emperor.name %></h1>

<p>Reign: <%= @emperor.reign_start&.year %> - <%= @emperor.reign_end&.year %></p>
<p>Birth Place: <%= @emperor.birth_place %></p>
<p>Bio: <%= @emperor.bio %></p>
<p>Fun Fact: <%= @emperor.fun_fact %></p>
<% if @emperor.image_url.present? %>
  <%= image_tag @emperor.image_url, alt: @emperor.name, style: "max-width: 300px;" %>
<% end %>

<%= link_to 'Back to List', emperors_path %>
</div>

app/views/gods/index.html.erb
<h1>Gods & Mythology</h1>

<div class="categories-container">
  <% @gods_by_realm.each do |realm, gods| %>
    <div class="category-group">
      <h2><%= realm %></h2>
      <ul>
        <% gods.each do |god| %>
          <li><%= link_to god.name, god_path(god) %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/gods/show.html.erb
<div class="fact-file-box">
  <h1><%= @god.name %></h1>

  <% if @god.greek_equivalent.present? %>
    <p><strong>Greek Equivalent:</strong> <%= @god.greek_equivalent %></p>
  <% end %>

  <p><strong>Realm:</strong> <%= @god.realm %></p>
  <p><strong>Symbols:</strong> <%= @god.symbols %></p>
  <p><strong>Family:</strong> <%= @god.family %></p>
  <p><%= simple_format(@god.story) %></p>
  <p><strong>Powers:</strong> <%= @god.powers %></p>
  <p><strong>Fun Fact:</strong> <%= @god.fun_fact %></p>
  <p><strong>How They Were Honored:</strong> <%= @god.honored %></p>
  <p><%= simple_format(@god.appearance) %></p>

  <% if @god.image_url.present? %>
    <%= image_tag @god.image_url, alt: @god.name %>
  <% end %>

  <div class="back-links">
    <%= link_to 'Back to Gods & Mythology', gods_path %> |
    <%= link_to 'Back to Home', root_path %>
  </div>
</div>

app/views/museums/index.html.erb
<h1>Museums With Roman Exhibitions</h1>

<div class="categories-container">
  <% @museums_by_region.each do |region, museum| %>
    <div class="category-group">
      <h2><%= region %></h2>
      <ul>
        <% museum.each do |museum| %>
          <li><%= link_to museum.name, museum_path(museum) %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

<%= link_to 'Back to Home', root_path %>

app/views/museums/show.html.erb
<div class="emperor-details">
<h1><%= @museum.name %></h1>

<p>Region: <%= @museum.region %> </p>
<p>Description: <%= @museum.description %></p>
<p>Address: <%= @museum.address %></p>
<% if @museum.web_link.present? %>
  <%= link_to @museum.web_link %>
<% end %>
<% if @museum.image_url.present? %>
  <%= image_tag @museum.image_url, alt: @museum.name, style: "max-width: 50%;" %>
<% end %>

<%= link_to 'Back to List', museums_path %>
</div>